---
name: release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Get version number from tag
        id: get_version
        uses: battila7/get-version-action@v2

      - name: Checkout code
        uses: actions/checkout@v5
        fetch-tags: true

      - name: Set up JDK 1.8
        uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: 8

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Publish package to Github Packages
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JAR_VERSION: ${{ steps.get_version.outputs.version-without-v  }}

      - name: Create GitHub release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: |
            build/libs/*.jar