---
name: Upload test data artifact

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  upload-test-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Upload test data
        uses: actions/upload-artifact@v4
        with:
          name: test-data
          path: test-data/ptb_resolutionphantom_fully_ismrmrd.h5
